package se.b3.healthtech.blackbird.blbaggregator.template;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import se.b3.healthtech.blackbird.blbaggregator.enums.ContentType;

import java.time.LocalDateTime;

@Data
@DynamoDBTable(tableName = "TemplateContainer")
public class TemplateContainer {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String creator;

    @DynamoDBAttribute
    private LocalDateTime created;

    @DynamoDBAttribute
    private int ordinal;

    @DynamoDBAttribute
    private ContentType contentType;

}
