package se.b3.healthtech.blackbird.blbaggregator.content;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import se.b3.healthtech.blackbird.blbaggregator.enums.ContentType;

import java.time.LocalDateTime;

@Data
@DynamoDBTable(tableName = "Content")
public class Content {

    //partition key
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    //sort key
    @DynamoDBRangeKey
    private String versionKey;

    @DynamoDBAttribute
    private String contentText;

    @DynamoDBAttribute
    private String creator;

    @DynamoDBAttribute
    private LocalDateTime created;

    @DynamoDBAttribute
    private ContentType contentType;
}
