package se.b3.healthtech.blackbird.blbaggregator.composition;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import se.b3.healthtech.blackbird.blbaggregator.enums.ContentType;

import java.time.LocalDateTime;
import java.util.List;

@Data
@DynamoDBTable(tableName = "Composition")
public class Composition {
    //partition key
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    //sort key
    @DynamoDBRangeKey
    private String versionKey;

    @DynamoDBAttribute
    private String contentText;

    @DynamoDBAttribute
    private String creator;

    @DynamoDBAttribute
    private LocalDateTime created;

    @DynamoDBAttribute
    private ContentType contentType;

    public List<Container> containerIdList;

}
