package se.b3.healthtech.blackbird.blbaggregator.composition;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import se.b3.healthtech.blackbird.blbaggregator.enums.ContentType;

import java.util.List;

@Data
@DynamoDBTable(tableName = "Container")
public class Container {
    //partition key
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    //sort key
    @DynamoDBRangeKey
    private String versionKey;

    @DynamoDBAttribute
    private String contentText;

    @DynamoDBAttribute
    private String userName;

    @DynamoDBAttribute
    private long created;

    @DynamoDBAttribute
    private int ordinal;

    @DynamoDBAttribute
    private ContentType contentType;

    @DynamoDBAttribute
    private List<String> containerObjectsList;

}
