package se.b3.healthtech.blackbird.blbaggregator.composition;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import se.b3.healthtech.blackbird.blbaggregator.enums.ContentType;

@Data
@DynamoDBTable(tableName = "ContainerObjects")
public class ContainerObjects {
    //partition key
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    //sort key
    @DynamoDBRangeKey
    private String versionKey;

    @DynamoDBAttribute
    private String userName;

    @DynamoDBAttribute
    private long created;

    @DynamoDBAttribute
    private ContentType contentType;

}

